### ISSUE TITLE
No match interview slots appear a different color (pink?)

### ISSUE THREAD

**Issue by domansyl** [tbpmig/mig-website#118]
if an active is signed up but no electee, or an electee but no active, make the slot pink or something obvious. My first idea was to have it show up pink on the interview slate, but if it could who up pink on the actives event sign ups that'd be cool too, it'd help actives sign up for times that there will for sure be an electee. 

It' be nice to have it this weekend.... obviously that's last minute. so eventually is fine too.

**Comment by mikehand** [comment]
eclipsed by #154
