### ISSUE TITLE
Fix interview UI (was: Change interview sign up on website to manual input by VPs)

### ISSUE THREAD

**Issue by domansyl** [tbpmig/mig-website#154]
Unless there is some better way of doing interview sign ups on the website, plan is to have VPs create a google doc and then a couple day before interviews, VPs should be able to sign everyone up on the website themselves.

Deadline: end of January if not earlier.

**Comment by mikehand** [comment]
Ok team, so refresh me on what we want in terms of the UI? Basically just a table view of who is signed up for what?

**Comment by domansyl** [comment]
who, when, where
Something that is of equal or greater value to the google spreadsheet we had before: https://docs.google.com/a/umich.edu/spreadsheet/ccc?key=0AlRZte8sljvDdFZPSE56V1VseTR1cEpIcjU2djJnYnc#gid=0
Though the spreadsheet doesn't show how electees rotate rooms. Also actives have to be able to see the questionnaire responses of the electee that signs up for their room and the electee that rotates into their room.
