### ISSUE TITLE
Organize interview feedback forms table results by color

### ISSUE THREAD

**Issue by domansyl** [tbpmig/mig-website#159]
@mrealm

**Comment by mikehand** [comment]
What?

**Comment by domansyl** [comment]
The table we use for Second Actives from the interview follow-up forms has green, yellow, and red I think depending on how their interviewers graded them. Benson wants that organized by color for easier use at Second Actives.

**Comment by mikehand** [comment]
So like make the following groups?:
-All green
-At least one yellow but no red
-At least one red

Michael Hand
Electrical Engineering: Systems Ph.D. Candidate
The University of Michigan
mikehand@umich.edu

**Comment by domansyl** [comment]
yea that way they're organized and in order for second actives, thanks!
