### ISSUE TITLE
Add ability to ask additional questions for event (interview) signup

### ISSUE THREAD

**Issue by mrealm** [tbpmig/mig-website#161]
It would be helpful to be able to add additional questions on a per-event basis.

E.g. For interviews, we would like to be able to ask if the interviewer(s) will be able to bring a tablet / laptop. (To be able to view the electee's survey response and progress)

**Comment by mikehand** [comment]
explain why including the directive to do so (bring a laptop, etc.) in the description is insufficient

**Comment by mrealm** [comment]
Reading something in a description and actually having to check a button,
make a selection from a pull down menu, or something similar are quite
different. Things in the description can be missed. Having a question that
is required will force the user to provide the information one way or the
other.

As far as for interviews, having a question of "Will you be able to bring a
tablet or laptop" would be helpful as we attempt to pair interviewers with
and without. So yes, it really is better to have the option to add
additional event signup questions on a per event or per event type basis.

Michael L. Benson
Ph.D. Candidate, Radiation Laboratory

The University of Michigan
Department of Electrical Engineering & Computer Science
1301 Beal Av. #3214
Ann Arbor, MI 48109-2122

Phone: (781) 249-1465
Email: mlbenson@umich.edu

**Comment by mikehand** [comment]
You're not pairing people though. People are just signing up for shifts...
