### ISSUE TITLE
Updates to the MindSET page 

### ISSUE THREAD

**Issue by rlneu** [tbpmig/mig-website#169]
1. In the FAQ section "When and where is MindSET organized?" The time we convey in all other materials is nine am. 
MindSET modules are organized three to four times a semester on Saturday morning from '9:00 am' to 12:00 pm on the University of Michigan's North Campus. Specific room numbers are conveyed to the schools at the beginning of each term. 

2. In the last section "What if my child misses a Saturday session?" there is a typo:

"We understand that attending all the sessions may not 'be' possible for students."

3. I (rlneu) attached the new parking map in an email to Mike Hand

4. This is the link to the feedback form. https://docs.google.com/forms/d/13A7YEZduqq-kBQ6SDW7YvNRg-heWPqF85SwWq1EvSGo/viewform?usp=send_form

**Comment by kylelady** [comment]
![lol totally brought this on yourself](https://i.imgur.com/NancU.gif)

**Comment by mikehand** [comment]
Turns out that the K-12 chairs can update the map directly. Click "update
mindset photos" from the mindset page:
https://tbp.engin.umich.edu/outreach/mindset/ and you'll be able to change
the parking photo.

Please attempt to verify that it works correctly.

**Comment by rlneu** [comment]
I was able to change the photo.  Thanks for implementing the other changes.
