### ISSUE TITLE
Add additional courses to tutoring offerings

### ISSUE THREAD

**Issue by MoDaum** [tbpmig/mig-website#182]
At https://tbp.engin.umich.edu/outreach/tutoring/, I would like to add 2 bullets
- ME (200 Level through PTS)
- AERO (through SGT)

**Comment by mikehand** [comment]
What aero courses? (same 200 level?)

**Comment by kylelady** [comment]
ALL OF THEM

**Comment by MoDaum** [comment]
I think 200 Level

On Mon, Feb 2, 2015 at 5:54 PM, Kyle Lady <notifications@github.com> wrote:

> ALL OF THEM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/182#issuecomment-72556449>.
>



-- 
Maureen Daum
BSE Computer Science, 2016
University of Michigan, Ann Arbor
