### ISSUE TITLE
Existing users are not bumped to electee status upon joining

### ISSUE THREAD

**Issue by dadrian** [tbpmig/mig-website#191]
If you had a user account before becoming an electee, you are not prompted to update your profile after becoming an electee. You can also not edit your own profile, and are given an error message  "Error: You must be logged in and a member to view member profiles" when you click on your own username in the upper-right.

**Steps to reproduce**:

1. Make an account
2. Wait two semesters
3. Be invited to TBP
4. Login
5. Attempt to update your profile/account

:sob:

**Comment by mikehand** [comment]
I've begun attempting to reproduce. Will report back next September

On Wednesday, September 23, 2015, Kyle Lady <notifications@github.com>
wrote:

> Assigned #191 <https://github.com/tbpmig/mig-website/issues/191> to
> @mikehand <https://github.com/mikehand>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/191#event-417134564>.
>


-- 
Michael Hand
Electrical Engineering/Control Systems M.S.E.
The University of Michigan
mikehand@umich.edu

**Comment by dadrian** [comment]
@kylelady, for the sake of debugging, we're going to need to kick @mikehand out of TBP until next September. That way he can be invited and continue past Step 3 in the steps to reproduce. I'm willing to help with this process.

@mikehand can you confirm this is the plan?

**Comment by kylelady** [comment]
ON IT.

**Comment by mikehand** [comment]
We'll need to come up with some form of scandal. Maybe we can borrow
something from the playbook of those two state reps...

On Wednesday, September 23, 2015, Kyle Lady <notifications@github.com>
wrote:

> ON IT.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/191#issuecomment-142661782>.
>


-- 
Michael Hand
Electrical Engineering/Control Systems M.S.E.
The University of Michigan
mikehand@umich.edu

**Comment by kylelady** [comment]
![](http://i.giphy.com/dxxj3hrmGmzVS.gif)

**Comment by mikehand** [comment]
Should work. Probably. But no promises

**Comment by dadrian** [comment]
Can confirm, is fixed.
