### ISSUE TITLE
Requiring UMID allows TBP to impersonate users at Chez Betty

### ISSUE THREAD

**Issue by dadrian** [tbpmig/mig-website#192]
Suggested fix: do not record UMID.

**Comment by mikehand** [comment]
Is not secret or privileged information. Is necessary for adding TBP to
transcript

On Friday, September 25, 2015, David Adrian <notifications@github.com>
wrote:

> Suggested fix: do not record UMID.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/192>.
>


-- 
Mike Hand

**Comment by kylelady** [comment]
Can confirm all of the above. UMID is considered equivalent to names re: FERPA, i.e., cannot be published alongside grades because it's not a private identifier.
