### ISSUE TITLE
Gender field on profile forces cisgender world view

### ISSUE THREAD

**Issue by dadrian** [tbpmig/mig-website#193]
Come on, we're better than that.

**Comment by mikehand** [comment]
1. Uhh no
2. You need not pick one that aligns with your biological sex
3. It's optional
4. Did I say "uhh no"
On Friday, September 25, 2015, David Adrian <notifications@github.com>
wrote:

> Come on, we're better than that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/193>.
>


-- 
Mike Hand
