### ISSUE TITLE
Google Calendar Events Contain HTML Tags

### ISSUE THREAD

**Issue by dadrian** [tbpmig/mig-website#194]
Steps to reproduce:

1. Homepage
2. Calendar->Google Calendar
3. Notice Calendar view is totally useless because there are 96 Interview Events on 10/6
4. Click Agenda
5. Select Second General
6. Click "Copy to my calendar"
![screen shot 2015-10-06 at 5 36 44 pm](https://cloud.githubusercontent.com/assets/1158264/10323404/d367722c-6c50-11e5-8a0b-8ff14644bb29.png)

**Comment by mikehand** [comment]
This is expected. It shows up correctly formatted in the event bubbles when
description is shown. Google does somethings funky with the descriptions in
editing the event

On Tuesday, October 6, 2015, David Adrian <notifications@github.com> wrote:

> Steps to reproduce:
>
>    1. Homepage
>    2. Calendar->Google Calendar
>    3. Notice Calendar view is totally useless because there are 96
>    Interview Events on 10/6
>    4. Click Agenda
>    5. Select Second General
>    6. Click "Copy to my calendar" [image: screen shot 2015-10-06 at 5 36
>    44 pm]
>    <https://cloud.githubusercontent.com/assets/1158264/10323404/d367722c-6c50-11e5-8a0b-8ff14644bb29.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/194>.
>


-- 
Mike Hand
