### ISSUE TITLE
Interview followups combined two electees together

### ISSUE THREAD

**Issue by MoDaum** [tbpmig/mig-website#195]
When I clicked on the interview followup for one electee, I was taken to the followup of a different electee, but it showed both of their names. 

Github doesn't support movies, which is terrible, so I attached pictures showing what I clicked on and where I was taken

<img width="1350" alt="after" src="https://cloud.githubusercontent.com/assets/6435122/10417477/f68081f0-700a-11e5-9604-bc93e4d0918d.png">
<img width="996" alt="before" src="https://cloud.githubusercontent.com/assets/6435122/10417478/f68e0140-700a-11e5-989e-0f5525de7925.png">

**Comment by mikehand** [comment]
There are two electees signed up for that interview...

Mike Hand

**Comment by mikehand** [comment]
[image: Inline image 1]

Mike Hand

**Comment by mikehand** [comment]
This behavior was, confusingly expected. May need to investigate race conditions in attendance limited events

**Comment by kylelady** [comment]
![](http://i.giphy.com/3b1JW7LxfsAKs.gif)
