### ISSUE TITLE
Old Profile, Current Electee

### ISSUE THREAD

**Issue by molender** [tbpmig/mig-website#196]
Vahid Rashidi (vrashidi) created a profile and began electing in a previous semester but never finished electing. He has been invited again and intends to elect this semester. However, he does not appear in the list of electees and his progress has not been recorded properly (among other issues with interviews).

**Comment by mikehand** [comment]
Not a bug. In fact intended and expected. You need to flag him as once
again electing from the "manage electees stopping electing page"

Please update your transition material

On Thursday, October 15, 2015, molender <notifications@github.com> wrote:

> Vahid Rashidi (vrashidi) created a profile and began electing in a
> previous semester but never finished electing. He has been invited again
> and intends to elect this semester. However, he does not appear in the list
> of electees and his progress has not been recorded properly (among other
> issues with interviews).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/196>.
>


-- 
Mike Hand

**Comment by molender** [comment]
Ah, didn't think to check that- thanks!

**Comment by molender** [comment]
He claims to have participated in an interview, but that shift appears empty in the Actives interview event and no longer exists in the Electee interview event. Is there any way to recover that shift and see if he was, in fact, registered? And would it have been possible for the interviewer to submit interview feedback?

**Comment by mikehand** [comment]
This semester or last?

On Thursday, October 15, 2015, molender <notifications@github.com> wrote:

> He claims to have participated in an interview, but that shift appears
> empty in the Actives interview event and no longer exists in the Electee
> interview event. Is there any way to recover that shift and see if he was,
> in fact, registered? And would it have been possible for the interviewer to
> submit interview feedback?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/196#issuecomment-148372497>.
>


-- 
Michael Hand
Electrical Engineering/Control Systems M.S.E.
The University of Michigan
mikehand@umich.edu

**Comment by molender** [comment]
This semester

**Comment by mikehand** [comment]
No longer a website issue.

On Thursday, October 15, 2015, molender <notifications@github.com> wrote:

> This semester
>
> > On Oct 15, 2015, at 8:55 AM, mikehand <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > This semester or last?
> >
> > On Thursday, October 15, 2015, molender <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > He claims to have participated in an interview, but that shift appears
> > > empty in the Actives interview event and no longer exists in the
> Electee
> > > interview event. Is there any way to recover that shift and see if he
> was,
> > > in fact, registered? And would it have been possible for the
> interviewer to
> > > submit interview feedback?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/tbpmig/mig-website/issues/196#issuecomment-148372497>.
> > >
> >
> >
> > --
> > Michael Hand
> > Electrical Engineering/Control Systems M.S.E.
> > The University of Michigan
> > mikehand@umich.edu <javascript:_e(%7B%7D,'cvml','mikehand@umich.edu');>
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/196#issuecomment-148377349>.
>


-- 
Michael Hand
Electrical Engineering/Control Systems M.S.E.
The University of Michigan
mikehand@umich.edu

**Comment by molender** [comment]
Actually, I think there might be an underlying website issue. Based upon responses from the electee and the interviewer, he had registered for the event, and the interviewer even completed the interview feedback form, which is no longer accessible (nor was it accessible prior to his change of status to "electing").

~Max

**Comment by mikehand** [comment]
What interview slot?

On Thursday, October 15, 2015, molender <notifications@github.com> wrote:

> Actually, I think there might be an underlying website issue. Based upon
> responses from the electee and the interviewer, he had registered for the
> event, and the interviewer even completed the interview feedback form,
> which is no longer accessible (nor was it accessible prior to his change of
> status to "electing").
>
> ~Max
>
> > On Oct 15, 2015, at 9:07 AM, mikehand <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > No longer a website issue.
> >
> > On Thursday, October 15, 2015, molender <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > This semester
> > >
> > > > On Oct 15, 2015, at 8:55 AM, mikehand <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > >
> > > > This semester or last?
> > > >
> > > > On Thursday, October 15, 2015, molender <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > >
> > > > > He claims to have participated in an interview, but that shift
> appears
> > > > > empty in the Actives interview event and no longer exists in the
> > > Electee
> > > > > interview event. Is there any way to recover that shift and see if
> he
> > > was,
> > > > > in fact, registered? And would it have been possible for the
> > > interviewer to
> > > > > submit interview feedback?
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/tbpmig/mig-website/issues/196#issuecomment-148372497>.
> > > > >
> > > >
> > > >
> > > > --
> > > > Michael Hand
> > > > Electrical Engineering/Control Systems M.S.E.
> > > > The University of Michigan
> > > > mikehand@umich.edu
> <javascript:_e(%7B%7D,'cvml','mikehand@umich.edu');>
> <javascript:_e(%7B%7D,'cvml','mikehand@umich.edu
> <javascript:_e(%7B%7D,'cvml','mikehand@umich.edu');>');>
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/tbpmig/mig-website/issues/196#issuecomment-148377349>.
> > >
> >
> >
> > --
> > Michael Hand
> > Electrical Engineering/Control Systems M.S.E.
> > The University of Michigan
> > mikehand@umich.edu <javascript:_e(%7B%7D,'cvml','mikehand@umich.edu');>
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/196#issuecomment-148405898>.
>


-- 
Michael Hand
Electrical Engineering/Control Systems M.S.E.
The University of Michigan
mikehand@umich.edu

**Comment by molender** [comment]
Tuesday, October 6, 10-10:30am

**Comment by mikehand** [comment]
Website did what it was supposed to. He wasn't signed up so when the shift
was in the past it deleted the shift. He wouldn't have been able to unsign
up after the event was in the past so he must not have signed up at all or
cancelled and then showed up anyway.

In any case I don't believe that the interviewer could have filled out an
evaluation if no one was listed as an interviewee.

Even if she somehow did it has since been deleted with the interviewee
shift.

Work with those involved to ensure he was interviewed properly and make a
dummy event to get him credit if so needed.

The website end of this is closed.

On Thursday, October 15, 2015, molender <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Tuesday, October 6, 10-10:30am
>
> > On Oct 15, 2015, at 10:38 AM, mikehand <notifications@github.com> wrote:
> >
> > What interview slot?
> >
> > On Thursday, October 15, 2015, molender <notifications@github.com>
> wrote:
> >
> > > Actually, I think there might be an underlying website issue. Based
> upon
> > > responses from the electee and the interviewer, he had registered for
> the
> > > event, and the interviewer even completed the interview feedback form,
> > > which is no longer accessible (nor was it accessible prior to his
> change of
> > > status to "electing").
> > >
> > > ~Max
> > >
> > > > On Oct 15, 2015, at 9:07 AM, mikehand <notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > >
> > > > No longer a website issue.
> > > >
> > > > On Thursday, October 15, 2015, molender <notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > >
> > > > > This semester
> > > > >
> > > > > > On Oct 15, 2015, at 8:55 AM, mikehand <notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > > > >
> > > > > > This semester or last?
> > > > > >
> > > > > > On Thursday, October 15, 2015, molender <
> notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > > > >
> > > > > > > He claims to have participated in an interview, but that shift
> > > appears
> > > > > > > empty in the Actives interview event and no longer exists in
> the
> > > > > Electee
> > > > > > > interview event. Is there any way to recover that shift and
> see if
> > > he
> > > > > was,
> > > > > > > in fact, registered? And would it have been possible for the
> > > > > interviewer to
> > > > > > > submit interview feedback?
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > > > >
> > >
> https://github.com/tbpmig/mig-website/issues/196#issuecomment-148372497>.
> > > > > > >
> > > > > >
> > > > > >
> > > > > > --
> > > > > > Michael Hand
> > > > > > Electrical Engineering/Control Systems M.S.E.
> > > > > > The University of Michigan
> > > > > > mikehand@umich.edu
> > > <javascript:_e(%7B%7D,'cvml','mikehand@umich.edu');>
> > > <javascript:_e(%7B%7D,'cvml','mikehand@umich.edu
> > > <javascript:_e(%7B%7D,'cvml','mikehand@umich.edu');>');>
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/tbpmig/mig-website/issues/196#issuecomment-148377349>.
> > > > >
> > > >
> > > >
> > > > --
> > > > Michael Hand
> > > > Electrical Engineering/Control Systems M.S.E.
> > > > The University of Michigan
> > > > mikehand@umich.edu <javascript:_e(%7B%7D,'cvml','mikehand@umich.edu
> ');>
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/tbpmig/mig-website/issues/196#issuecomment-148405898>.
> > >
> >
> >
> > --
> > Michael Hand
> > Electrical Engineering/Control Systems M.S.E.
> > The University of Michigan
> > mikehand@umich.edu
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/196#issuecomment-148407370>.
>


-- 
Michael Hand
Electrical Engineering/Control Systems M.S.E.
The University of Michigan
mikehand@umich.edu

**Comment by mikehand** [comment]
In talking with Kyle, new hypothesis:

1. Vahid was not re-added as electing until a month after he should have
been
2. Vahid signed up for interview
3. @MoDaum updated her electees that had stopped electing
4. While processing the above Vahid was still listed as no longer electing
and was therefore booted from all still-open events he was signed up for
(which would include interviews)
5. Shift now empty, website culled the shifts. Shift and follow up deleted
as part of now stale shift

So the root issue here is the first part. I'll look into making it not
remove electees that are not newly no longer electing but this is never an
issue if he gets added on time.

Issue closed I'll make a new one for the relevant feature request

On Thursday, October 15, 2015, Mike Hand <mikehand@umich.edu
<javascript:_e(%7B%7D,'cvml','mikehand@umich.edu');>> wrote:

> Website did what it was supposed to. He wasn't signed up so when the shift
> was in the past it deleted the shift. He wouldn't have been able to unsign
> up after the event was in the past so he must not have signed up at all or
> cancelled and then showed up anyway.
>
> In any case I don't believe that the interviewer could have filled out an
> evaluation if no one was listed as an interviewee.
>
> Even if she somehow did it has since been deleted with the interviewee
> shift.
>
> Work with those involved to ensure he was interviewed properly and make a
> dummy event to get him credit if so needed.
>
> The website end of this is closed.
>
> On Thursday, October 15, 2015, molender <notifications@github.com> wrote:
>
>> Tuesday, October 6, 10-10:30am
>>
>> > On Oct 15, 2015, at 10:38 AM, mikehand <notifications@github.com>
>> wrote:
>> >
>> > What interview slot?
>> >
>> > On Thursday, October 15, 2015, molender <notifications@github.com>
>> wrote:
>> >
>> > > Actually, I think there might be an underlying website issue. Based
>> upon
>> > > responses from the electee and the interviewer, he had registered for
>> the
>> > > event, and the interviewer even completed the interview feedback form,
>> > > which is no longer accessible (nor was it accessible prior to his
>> change of
>> > > status to "electing").
>> > >
>> > > ~Max
>> > >
>> > > > On Oct 15, 2015, at 9:07 AM, mikehand <notifications@github.com
>> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>> > > >
>> > > > No longer a website issue.
>> > > >
>> > > > On Thursday, October 15, 2015, molender <notifications@github.com
>> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>> > > >
>> > > > > This semester
>> > > > >
>> > > > > > On Oct 15, 2015, at 8:55 AM, mikehand <notifications@github.com
>> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
>> > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
>> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
>> wrote:
>> > > > > >
>> > > > > > This semester or last?
>> > > > > >
>> > > > > > On Thursday, October 15, 2015, molender <
>> notifications@github.com
>> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
>> > > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
>> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
>> wrote:
>> > > > > >
>> > > > > > > He claims to have participated in an interview, but that shift
>> > > appears
>> > > > > > > empty in the Actives interview event and no longer exists in
>> the
>> > > > > Electee
>> > > > > > > interview event. Is there any way to recover that shift and
>> see if
>> > > he
>> > > > > was,
>> > > > > > > in fact, registered? And would it have been possible for the
>> > > > > interviewer to
>> > > > > > > submit interview feedback?
>> > > > > > >
>> > > > > > > —
>> > > > > > > Reply to this email directly or view it on GitHub
>> > > > > > > <
>> > > > >
>> > >
>> https://github.com/tbpmig/mig-website/issues/196#issuecomment-148372497>.
>> > > > > > >
>> > > > > >
>> > > > > >
>> > > > > > --
>> > > > > > Michael Hand
>> > > > > > Electrical Engineering/Control Systems M.S.E.
>> > > > > > The University of Michigan
>> > > > > > mikehand@umich.edu
>> > > <javascript:_e(%7B%7D,'cvml','mikehand@umich.edu');>
>> > > <javascript:_e(%7B%7D,'cvml','mikehand@umich.edu
>> > > <javascript:_e(%7B%7D,'cvml','mikehand@umich.edu');>');>
>> > > > > > —
>> > > > > > Reply to this email directly or view it on GitHub.
>> > > > > >
>> > > > >
>> > > > > —
>> > > > > Reply to this email directly or view it on GitHub
>> > > > > <
>> > >
>> https://github.com/tbpmig/mig-website/issues/196#issuecomment-148377349>.
>> > > > >
>> > > >
>> > > >
>> > > > --
>> > > > Michael Hand
>> > > > Electrical Engineering/Control Systems M.S.E.
>> > > > The University of Michigan
>> > > > mikehand@umich.edu <javascript:_e(%7B%7D,'cvml','mikehand@umich.edu
>> ');>
>> > > > —
>> > > > Reply to this email directly or view it on GitHub.
>> > > >
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> https://github.com/tbpmig/mig-website/issues/196#issuecomment-148405898>.
>> > >
>> >
>> >
>> > --
>> > Michael Hand
>> > Electrical Engineering/Control Systems M.S.E.
>> > The University of Michigan
>> > mikehand@umich.edu
>> > —
>> > Reply to this email directly or view it on GitHub.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tbpmig/mig-website/issues/196#issuecomment-148407370>
>> .
>>
>
>
> --
> Michael Hand
> Electrical Engineering/Control Systems M.S.E.
> The University of Michigan
> mikehand@umich.edu
>
>

-- 
Michael Hand
Electrical Engineering/Control Systems M.S.E.
The University of Michigan
mikehand@umich.edu

**Comment by molender** [comment]
I'm not quite sure how that would have happened or if I follow completely,
but if you know what's wrong then great. Everything seems to be resolved
for now. Thanks again!

~Max
