### ISSUE TITLE
DB Performance (aka new server)

### ISSUE THREAD

**Issue by kylelady** [tbpmig/mig-website#2]
It is not fast.

**Comment by mikehand** [comment]
Was there anything more to do here besides the migration?

**Comment by kylelady** [comment]
Unlikely?

**Comment by kylelady** [comment]
The infrastructure is there, but the application needs modification. See also: https://devcenter.heroku.com/articles/django-memcache#modify-the-application

**Comment by mikehand** [comment]
The most offending pages have been dealt with. Will re-open if new performance issues arise.
![image](http://bigfitdeal.com/blog/wp-content/uploads/2014/05/joeydoor.gif)
