### ISSUE TITLE
Google Calendar export automatically exports to UMich Google Account

### ISSUE THREAD

**Issue by dadrian** [tbpmig/mig-website#202]
It would be nice to be able to export them to the `@gmail` account I use for my calendar, instead.

**Comment by mikehand** [comment]
You can change this in your account preferences

On Monday, February 1, 2016, David Adrian <notifications@github.com> wrote:

> It would be nice to be able to export them to the @gmail
> <https://github.com/gmail> account I use for my calendar, instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/202>.
>


-- 
Mike Hand

**Comment by dadrian** [comment]
:+1:
