### ISSUE TITLE
Feature Request: Allow meetings with virtual agendas (e.g. general meetings) to provide link to agenda

### ISSUE THREAD

**Issue by mrealm** [tbpmig/mig-website#203]
If an event uses the website to sign in, it would be nice if a new field could be added to the event, a link to the event's agenda, that would be displayed either upon signing into the event OR along with the prompt to sign in on the main page (e.g. change  "Second General is going on. Click here to sign in." to "Second General is going on. Click here to sign in. Click here to view the agenda."

**Comment by kylelady** [comment]
Wait, we don't do that?

**Comment by mikehand** [comment]
I mean you can link the agenda in the description...

It's not structured data like Benson wants

On Tuesday, February 2, 2016, Kyle Lady <notifications@github.com> wrote:

> Wait, we don't do that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/203#issuecomment-178964511>.
>


-- 
Mike Hand

**Comment by kylelady** [comment]
Oh. I thought we did that.
