### ISSUE TITLE
Add OCSP stapling to HTTPS site configuration

### ISSUE THREAD

**Issue by dadrian** [tbpmig/mig-website#210]
Mostly just creating this to track what I'm doing.

https://en.wikipedia.org/wiki/OCSP_stapling

**Comment by dadrian** [comment]
It turns out this can't be done without updating Apache to at least 2.3.3, which I'm pretty sure is not easily accomplished on our current setup. @kylelady, thoughts?

**Comment by mikehand** [comment]
@kylelady Is this something we can roll into the update-all-the things, thing?

**Comment by kylelady** [comment]
Sure. Buy me some alcohol, and I'll gladly deal with yet another "UPDATE
ALL THE THINGS" fiasco.
