### ISSUE TITLE
Document how to run the web site locally

### ISSUE THREAD

**Issue by dadrian** [tbpmig/mig-website#213]

**Comment by mrealm** [comment]
@kylelady please send David and I a new db export.

**Comment by kylelady** [comment]
done

**Comment by kylelady** [comment]
nvm I only sent the db dump. I assumed @mrealm had opened a separate issue for the separate task.

**Comment by mrealm** [comment]
@kylelady nope, that was a sub-task to the overall getting going

**Comment by kylelady** [comment]
I figured that part out.

**Comment by mikehand** [comment]
That's why the issue is now open

On Wednesday, April 13, 2016, Kyle Lady <notifications@github.com> wrote:

> I figured that part out.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/213#issuecomment-209523992>
>


-- 
Michael Hand
Electrical Engineering/Control Systems M.S.E.
The University of Michigan
mikehand@umich.edu

**Comment by dadrian** [comment]
:+1:
