### ISSUE TITLE
requirements.txt is broken

### ISSUE THREAD

**Issue by dadrian** [tbpmig/mig-website#214]
Running `pip install -r requirements.txt` results in errors due to several packages not existing. Example errors message:

```
Could not find a version that satisfies the requirement django-ajax==2.2.12 (from -r requirements.txt (line 4)) (from versions: 0.1.0, 0.1.0.post2, 0.1.1.post1, 0.2.0)
```

The full list of packages it errors on:
- `django-ajax==2.2.12`
- `PIL==1.1.7`

**Comment by mikehand** [comment]
@kylelady

can you check what versions of those are actually installed?


Mike Hand

**Comment by kylelady** [comment]
Those are the versions installed. Not sure how to force those versions to install. This is what `pip freeze` is supposed to make possible.

**Comment by dadrian** [comment]
Maybe one of these was unpublished?
On Thu, Apr 14, 2016 at 9:31 AM Kyle Lady <notifications@github.com> wrote:

> Those are the versions installed. Not sure how to force those versions to
> install. This is what pip freeze is supposed to make possible.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/214#issuecomment-209941755>
>
-- 
David Adrian
https://davidadrian.org

**Comment by dadrian** [comment]
@kylelady can you run `pip show django-ajax` on prod? I think the the package names changed slightly, and django-ajax now points to a different library.

**Comment by kylelady** [comment]
<pre>migweb webdev@tbp:~$ pip show django-ajax
---
Metadata-Version: 1.1
Name: django-ajax
Version: 2.2.12
Summary: Powerful and easy AJAX framework for django applications.
Home-page: https://github.com/yceruto/django-ajax
Author: Yonel Ceruto Glez
Author-email: yceruto@abalt.org
License: MIT License
Location: /home/webdev/.virtualenvs/migweb/lib/python2.7/site-packages
Requires: setuptools, django
Classifiers:
  Environment :: Web Environment
  Framework :: Django
  Intended Audience :: Developers
  License :: OSI Approved :: MIT License
  Operating System :: OS Independent
  Programming Language :: Python
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Topic :: Internet :: WWW/HTTP
  Topic :: Internet :: WWW/HTTP :: Dynamic Content</pre>

**Comment by mikehand** [comment]
So did this get resolved? Is there actually still a bug here?

**Comment by dadrian** [comment]
I still don't know how to run the website locally. ¯\\_(ツ)_/¯
