### ISSUE TITLE
Calendar name out of date

### ISSUE THREAD

**Issue by kevingreenman** [tbpmig/mig-website#235]
Can you change the name of the "Corporate Events" calendar to be the "Professional Development Events" calendar so it more accurately reflects the events it contains?

**Comment by kylelady** [comment]
Are you talking about the Google Calendar named "[TBP] Corporate"?

**Comment by kevingreenman** [comment]
Yes. Sorry if that was unclear - I was going off of the options in the dropdown menu when you're creating an event.

**Comment by kevingreenman** [comment]
Is this something you can do?

**Comment by mikehand** [comment]
I mean if you mean the name of the actual google calendar then anyone with
access eg the Pres can do that. The drop down is merely something on the
site which could be changed but won’t impact the real calendar

**Comment by kevingreenman** [comment]
Noted. Please change the drop down, and I'll ask the president to change the google calendar name

**Comment by mikehand** [comment]
Website end fixed
